In [2]:
from sklearn import metrics, datasets
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
from matplotlib.pylab import rcParams
import numpy as np
%matplotlib inline

## 回歸問題
常見的評估指標有
- MAE
- MSE
- R-square

In [5]:
X, y = datasets.make_regression(n_features=1, random_state=42, noise=4) # 生成資料
X


array([[ 0.93128012],
       [ 0.08704707],
       [-1.05771093],
       [ 0.31424733],
       [-0.47917424],
       [ 0.64768854],
       [-0.46341769],
       [ 0.54256004],
       [ 0.61167629],
       [ 1.0035329 ],
       [ 0.8219025 ],
       [ 1.53803657],
       [ 0.73846658],
       [-0.21967189],
       [-0.8084936 ],
       [ 0.09176078],
       [-1.95967012],
       [ 0.51326743],
       [ 1.03099952],
       [-2.6197451 ],
       [ 0.49671415],
       [ 0.09707755],
       [-0.46572975],
       [ 0.91540212],
       [ 1.56464366],
       [ 1.46564877],
       [-0.60063869],
       [-0.03582604],
       [-0.60170661],
       [-1.19620662],
       [ 0.35711257],
       [ 0.37569802],
       [ 0.26105527],
       [-0.5297602 ],
       [-0.90802408],
       [ 0.19686124],
       [-0.29900735],
       [ 0.36163603],
       [ 0.82254491],
       [-0.29169375],
       [ 0.36139561],
       [-0.676922  ],
       [ 1.52302986],
       [-0.51827022],
       [-0.23415337],
       [-0

In [11]:
tx = [4,10]
ty = [2,0]

metrics.mean_absolute_error(tx, ty) # (10 + 2) /2
metrics.mean_squared_error(tx, ty) # (10^2 + 2^2)/2

6.0

In [17]:
X, y = datasets.make_regression(n_features=1, random_state=42, noise=4) # 生成資料
model = LinearRegression() # 建立回歸模型
model.fit(X, y) # 將資料放進模型訓練
prediction = model.predict(X) # 進行預測
prediction

array([  40.34302144,    4.19336052,  -44.82463681,   13.92196864,
        -20.05196866,   28.19976374,  -19.37728083,   23.69821121,
         26.65773622,   43.43685133,   35.65952358,   66.32404624,
         32.08683666,   -8.94020046,  -34.15326849,    4.39519929,
        -83.44610398,   22.44391545,   44.61295924, -111.7102032 ,
         21.7351118 ,    4.62286099,  -19.47628218,   39.66313291,
         67.46334925,   63.2244349 ,  -25.25301918,   -1.06800796,
        -25.29874711,  -50.75495713,   15.75743795,   16.55325801,
         11.64430971,  -22.21803585,  -38.41511637,    8.89555137,
        -12.33730754,   15.9511301 ,   35.68703118,  -12.02414261,
         15.94083544,  -28.51943454,   65.68146599,  -21.72604009,
         -9.5602909 ,  -16.32383999,  -12.42707205,  -27.15767739,
         14.54301353,    9.40948672,  -13.56429239,    0.68500193,
         -9.5595879 ,   63.74877183,  -16.02299543,   15.17961916,
         14.65058997,   -7.48378366,   -9.57886424,  -84.64071

In [25]:
X.shape
y.shape
prediction.shape
# X
# y

(100,)

我們隨機生成(X, y)資料，然後使用線性回歸模型做預測，再使用 MAE, MSE, R-square 評估

In [26]:
X, y = datasets.make_regression(n_features=1, random_state=42, noise=4) # 生成資料
model = LinearRegression() # 建立回歸模型
model.fit(X, y) # 將資料放進模型訓練
prediction = model.predict(X) # 進行預測
mae = metrics.mean_absolute_error(prediction, y) # 使用 MAE 評估
mse = metrics.mean_squared_error(prediction, y) # 使用 MSE 評估
r2 = metrics.r2_score(prediction, y) # 使用 r-square 評估
print("MAE: ", mae)
print("MSE: ", mse)
print("R-square: ", r2)

MAE:  2.841797252565566
MSE:  12.48868006739824
R-square:  0.9916581036260311


## 分類問題
常見的評估指標有
- AUC
- F1-Score (Precision, Recall)

In [27]:
cancer = datasets.load_breast_cancer() # 我們使用 sklearn 內含的乳癌資料集
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=50, random_state=0)

In [37]:
cancer.data.shape
# cancer.target.shape
# X_train.shape
# X_test.shape

(569, 30)

In [38]:
print(y_test) # 測試集中的 label

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 0 1 0 1 1 0 1 1 1 0]


In [39]:
y_pred = np.random.random((50,)) # 我們先隨機生成 50 筆預測值，範圍都在 0~1 之間，代表機率值

In [40]:
print(y_pred)

[0.81583826 0.8373962  0.7675552  0.48210989 0.59058989 0.16625959
 0.27355514 0.60175917 0.09097857 0.14524841 0.79996926 0.05166377
 0.64044246 0.09378169 0.38875061 0.32953521 0.50003656 0.80577498
 0.91180976 0.54983917 0.58455854 0.13017717 0.20166977 0.24687409
 0.34811908 0.54510696 0.82844976 0.93915789 0.02530101 0.30987267
 0.84828706 0.74930243 0.90330067 0.54791851 0.36038873 0.94628835
 0.75103411 0.84465804 0.09534691 0.20052884 0.45300974 0.7381253
 0.78924719 0.52682527 0.66625964 0.75637315 0.76020064 0.64895118
 0.06682719 0.89891801]


### AUC

In [41]:
auc = metrics.roc_auc_score(y_test, y_pred) # 使用 roc_auc_score 來評估。 **這邊特別注意 y_pred 必須要放機率值進去!**
print("AUC: ", auc) # 得到結果約 0.5，與亂猜的結果相近，因為我們的預測值是用隨機生成的

AUC:  0.3378607809847199


In [42]:
threshold = 0.5
np.where(y_pred>threshold, 1, 0)

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1])

## F1-Score

In [43]:
threshold = 0.5 
y_pred_binarized = np.where(y_pred>threshold, 1, 0) # 使用 np.where 函數, 將 y_pred > 0.5 的值變為 1，小於 0.5 的為 0
f1 = metrics.f1_score(y_test, y_pred_binarized) # 使用 F1-Score 評估
precision = metrics.precision_score(y_test, y_pred_binarized) # 使用 Precision 評估
recall  = metrics.recall_score(y_test, y_pred_binarized) # 使用 recall 評估
print("F1-Score: ", f1) 
print("Precision: ", precision)
print("Recall: ", recall)

F1-Score:  0.5573770491803278
Precision:  0.5666666666666667
Recall:  0.5483870967741935


## 作業
請參考 F1-score 的公式與[原始碼](https://github.com/scikit-learn/scikit-learn/blob/bac89c2/sklearn/metrics/classification.py#L620)，試著寫出 F2-Score 的計算函數